

def build(bld):
    bld.DefineGem(
        # General
        includes                = [ '.',
                                    bld.Path('Code/CryEngine/CryCommon'),
                                    bld.Path('Code/CryEngine/CryAction'),
                                    bld.Path('Code/Sandbox/Plugins/EditorCommon'),
                                    bld.Path('Code/Sandbox/Editor'),
                                    bld.Path('Code/Sandbox/Editor/Include')],
        use                     = ['AzGameFramework', 'EditorUI_QT', 'EditorCommon', 'EditorCore'],
        defines                 = ['DYNAMIC_CONTENT_EDITOR', 'EDITOR_COMMON_IMPORTS'],
        # Platform Specific
        android_use             = ['AndroidLauncher'],

        # ==============================
        # iOS
        # 'ios_output_file_name' must match both
        # 'executable_name' in 'project.json' and
        # 'Executable file' in '../Resources/IOSLauncher/Info.plist'
        # ==============================
        ios_file_list           = ['birdeye_ios.waf_files'],

        # ==============================
        # AppleTV
        # 'appletv_output_file_name' must match both
        # 'executable_name' in 'project.json' and
        # 'Executable file' in '../Resources/AppleTVLauncher/Info.plist'
        # ==============================
        appletv_file_list       = ['birdeye_appletv.waf_files'],

        darwin_file_list        = ['birdeye_mac.waf_files'],

       
       

        # Testing
        test_all_file_list      = ['birdeye_tests.waf_files'],

        # Add additional custom build options here

    )
